spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:security-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:username}
    password: ${DB_PAWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/logs.log